/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TButton: typeof import('./src/components/Button/TButton.vue')['default']
    TDataTable: typeof import('./src/components/DataTable/TDataTable.vue')['default']
    TIcon: typeof import('./src/components/Icon/TIcon.vue')['default']
    TInput: typeof import('./src/components/Input/TInput.vue')['default']
    TPagination: typeof import('./src/components/Pagination/TPagination.vue')['default']
  }
}
